### ISSUE TITLE
lavasearch2 error with lme and random slopes

### ISSUE THREAD

**Issue by stueller** [bozenne/lavaSearch2#1]
```
library(nlme)
data("Orthodont")

# random intercepts only
m0 <- lme(distance ~ age + Sex, data = Orthodont, random = ~ 1 | Subject)
model_parameters(m0) 
model_parameters(m0, df_method="satterthwaite")

# random intercepts and random slopes
m1 <- lme(distance ~ age + Sex, data = Orthodont, random = ~ age | Subject)
model_parameters(m1) 
model_parameters(m1, df_method="satterthwaite")

```

The last call yields an error:

![image](https://user-images.githubusercontent.com/3276809/96634961-7b8ce800-12d8-11eb-9162-3763928958e3.png)

**Comment by bozenne** [comment]
I could not run your example and the function model_parameters is not part of lavaSearch2 (at least not in the latest version, as I remember). 
For Satterthwaite correction for models with random slopes see lme4 and lmerTest packages
